package:
  name: requests
  version: 2021.11.3

source:
  url: https://github.com/bartbroere/pyodide-requests/archive/refs/heads/main.tar.gz
  sha256: 6585782dcdf701c8497ff1a4bab4b3238c9044d11f1a3f91fb103f5c003be897

test:
  imports:
    - requests
