package:
  name: requests
  version: 2021.11.2

source:
  url: https://github.com/bartbroere/pyodide-requests/archive/refs/heads/main.tar.gz
  sha256: c0bd341a04151935bb4d668cc7da0a0ea8d649bf896364f294b58341b9ffff29

test:
  imports:
    - requests
