package:
  name: requests
  version: 2021.11.3

source:
  url: https://github.com/bartbroere/pyodide-requests/archive/refs/heads/main.tar.gz
  sha256: 8bfbebf0a225dc7058eeaaf066ae44e9a5f29c893f12bce1f3690dfec9360cb8

test:
  imports:
    - requests
