package:
  name: requests
  version: 2021.11.3

source:
  url: https://github.com/bartbroere/pyodide-requests/archive/refs/heads/main.tar.gz
  sha256: e96ee12b3834f77a639e439ac3cc1922e7a8e39c5bbb36ca15e34e0e63ec9e87

test:
  imports:
    - requests
