package:
  name: fastparquet
  version: 2023.10.1
  top-level:
    - fastparquet
requirements:
  run:
    - cramjam
    - numpy
    - pandas
    - fsspec
    - packaging
source:
  url: https://files.pythonhosted.org/packages/e4/be/66b9b0c1b1ad092940efbca5e12402e5e92c55360dce876a65ed3cbb78ff/fastparquet-2023.10.1.tar.gz
  sha256: 076fedfba2b56782b4823c1d351424425cfeaa5b8644c542416ca1363fe6d921
about:
  home: https://github.com/dask/fastparquet/
  PyPI: https://pypi.org/project/fastparquet
  summary: Python support for Parquet file format
  license: Apache License 2.0
