package:
  name: libprotobuf
  version: 22.4

source:
  url: https://github.com/protocolbuffers/protobuf/releases/download/v22.4/protobuf-22.4.tar.gz
  sha256: 518978c930ce1cede2e48e698e9933e92946c002477748c3c54f0ddf21b31608

build:
  type: static_library
  script: |
    emconfigure ./configure \
        CFLAGS="-fPIC" \
        --disable-xz \
        --disable-xzdec \
        --disable-lzmadec \
        --disable-lzmainfo \
        --disable-lzma-links \
        --disable-scripts \
        --disable-doc \
        --enable-shared=no \
        --disable-dependency-tracking \
        --prefix=${WASM_LIBRARY_DIR}

    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
