package:
  name: orjson
  version: 3.9.12
  top-level:
    - orjson
source:
  url: https://files.pythonhosted.org/packages/3d/27/6a821fc97a2b68705cba3158e5ddb300938500a8c2b19dc084f6d43587d4/orjson-3.9.12.tar.gz
  sha256: da908d23a3b3243632b523344403b128722a5f45e278a8343c2bb67538dff0e4
requirements:
  executable:
    - rustup
build:
  script: export RUSTFLAGS="-Z link-native-libraries=yes"
about:
  home: https://github.com/ijl/orjson
  PyPI: https://pypi.org/project/orjson
  summary:
    Fast, correct Python JSON library supporting dataclasses, datetimes, and
    numpy
  license: Apache-2.0 OR MIT
