package:
  name: ruamel.yaml
  version: 0.18.5
  top-level:
    - ruamel
source:
  url: https://files.pythonhosted.org/packages/57/db/4b74a29f5fd175aea3ff0d95f8230d9bb8a54e38d963c6f96065b9e2eef3/ruamel.yaml-0.18.5-py3-none-any.whl
  sha256: a013ac02f99a69cdd6277d9664689eb1acba07069f912823177c5eced21a6ada
test:
  imports:
    - ruamel.yaml
about:
  home: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree
  PyPI: https://pypi.org/project/ruamel.yaml
  summary:
    ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation
    of comments, seq/map flow style, and map key order
  license: MIT license
