package:
  name: certifi
  version: 2024.7.4
  top-level:
    - certifi
source:
  url: https://files.pythonhosted.org/packages/ba/06/a07f096c664aeb9f01624f858c3add0a4e913d6c96257acb4fce61e7de14/certifi-2024.2.2-py3-none-any.whl
  sha256: c198e21b1289c2ab85ee4e67bb4b4ef3ead0892059901a8d5b622f24a1101e90
about:
  home: https://github.com/certifi/python-certifi
  PyPI: https://pypi.org/project/certifi
  summary:
    Certifi provides Mozilla’s carefully curated collection of Root Certificates
    for validating the trustworthiness of SSL certificates while verifying the identity
    of TLS hosts.
  license: "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)"
