package:
  name: fsspec
  version: 2023.12.2
  top-level:
    - fsspec
source:
  url: https://files.pythonhosted.org/packages/70/25/fab23259a52ece5670dcb8452e1af34b89e6135ecc17cd4b54b4b479eac6/fsspec-2023.12.2-py3-none-any.whl
  sha256: d800d87f72189a745fa3d6b033b9dc4a34ad069f60ca60b943a63599f5501960
about:
  home: http://github.com/fsspec/filesystem_spec
  PyPI: https://pypi.org/project/fsspec
  summary: File-system specification
  license: BSD
