package:
  name: fonttools
  version: 4.47.2
  top-level:
    - fontTools
source:
  url: https://files.pythonhosted.org/packages/af/2f/c34b0f99d46766cf49566d1ee2ee3606e4c9880b5a7d734257dc61c804e9/fonttools-4.47.2-py3-none-any.whl
  sha256: 7eb7ad665258fba68fd22228a09f347469d95a97fb88198e133595947a20a184
about:
  home: http://github.com/fonttools/fonttools
  PyPI: https://pypi.org/project/fontTools
  summary: Tools to manipulate font files
  license: MIT
