package:
  name: peewee
  version: 3.17.0
  top-level:
    - peewee
requirements:
  host:
    - cffi
  run:
    - sqlite3
    - cffi
source:
  url: https://files.pythonhosted.org/packages/6a/30/a727bb1420076b3c14b60911d111f0fc0449d31a1123a1ad18878a7a4e40/peewee-3.17.0.tar.gz
  sha256: 3a56967f28a43ca7a4287f4803752aeeb1a57a08dee2e839b99868181dfb5df8
about:
  home: https://github.com/coleifer/peewee/
  PyPI: https://pypi.org/project/peewee/
  summary:
    Peewee is a simple and small ORM. It has few (but expressive) concepts,
    making it easy to learn and intuitive to use.
  license: MIT License
