package:
  name: protobuf
  version: 5.26.0
  top-level:
    - google

source:
  url: https://files.pythonhosted.org/packages/cf/e6/fd8adea47dd18a46662002faf8aa6653ac37f39c93b39343a8e9bc7b8bea/protobuf-5.26.0rc3.tar.gz
  sha256: 1d6da042e92a6b1b2f495c187aa469e55839dd9f2b6520a02cb98472d4ba4c6e

about:
  home: https://github.com/protocolbuffers/protobuf
  PyPI: https://pypi.org/project/protobuf
  summary: Protocol Buffers are a language-neutral, platform-neutral extensible mechanism for serializing structured data
  license: Custom

build:
  cflags: "-Wno-int-conversion"

extra:
  recipe-maintainers:
    - bartbroere
