package:
  name: protobuf
  version: 5.26.0
  top-level:
    - google

source:
  url: https://files.pythonhosted.org/packages/ea/ab/ae590cd71f5a50cd9e0979593e217529b532a001e46c2dd0811c8697f4ad/protobuf-5.26.0.tar.gz
  sha256: 82f5870d74c99addfe4152777bdf8168244b9cf0ac65f8eccf045ddfa9d80d9b

about:
  home: https://github.com/protocolbuffers/protobuf
  PyPI: https://pypi.org/project/protobuf
  summary: Protocol Buffers are a language-neutral, platform-neutral extensible mechanism for serializing structured data
  license: Custom

build:
  cflags: "-Wno-int-conversion"

extra:
  recipe-maintainers:
    - bartbroere
