package:
  name: protobuf
  version: 4.25.3
  top-level:
    - google

source:
  url: https://files.pythonhosted.org/packages/5e/d8/65adb47d921ce828ba319d6587aa8758da022de509c3862a70177a958844/protobuf-4.25.3.tar.gz
  sha256: 25b5d0b42fd000320bd7830b349e3b696435f3b329810427a6bcce6a5492cc5c

about:
  home: https://github.com/protocolbuffers/protobuf
  PyPI: https://pypi.org/project/protobuf
  summary: Protocol Buffers are a language-neutral, platform-neutral extensible mechanism for serializing structured data
  license: Custom
extra:
  recipe-maintainers:
    - bartbroere
