package:
  name: zengl
  version: 2.3.0
  top-level:
    - zengl
    - _zengl
    - _zengl_js

source:
  url: https://files.pythonhosted.org/packages/e2/dc/a68e3e069700ead6b7cd7e93d362ce0aaf1e7d53b3a34f7dc56177bc4c9a/zengl-2.3.0.tar.gz
  sha256: 45e9ccc4c36b141834197f173d90109ca49061801b74c47466f127c81b2fdf27

about:
  home: https://github.com/szabolcsdombi/zengl/
  PyPI: https://pypi.org/project/zengl
  summary: Self-Contained OpenGL Rendering Pipelines for Python
  license: MIT
