package:
  name: MarkupSafe
  version: 2.1.4
  top-level:
    - markupsafe
source:
  sha256: 3aae9af4cac263007fd6309c64c6ab4506dd2b79382d9d19a1994f9240b8db4f
  url: https://files.pythonhosted.org/packages/fb/5a/fb1326fe32913e663c8e2d6bdf7cde6f472e51f9c21f0768d9b9080fe7c5/MarkupSafe-2.1.4.tar.gz
about:
  home: https://palletsprojects.com/p/markupsafe/
  PyPI: https://pypi.org/project/MarkupSafe
  summary: Safely add untrusted strings to HTML/XML markup.
  license: BSD-3-Clause
